Repository SauravMukherjee44/Aec-Library-Website, pull requests merged in 2021-10, with the labels that each got.

#69 Aligned checkbox in a straight line
  assets/css/donate-book.css
Labels: Hacktoberfest

#70 Added authors dropdown list with names of a few popular authors
  assets/css/style.css
  index.html
Labels: Hacktoberfest, Hacktoberfest-accepted

#76 added favicon for donate-book section
  public/donate-book.html
Labels: Hacktoberfest, Hacktoberfest-accepted

#98 made navbar items responvie
  resource.css
  resource.html
Labels: Hacktoberfest, Hacktoberfest-accepted

#99 Made all input fields uniform
  assets/css/style.css
Labels: Hacktoberfest, Hacktoberfest-accepted

#118 Added More Labels
  public/donate-book.html
Labels: Hacktoberfest-accepted

#136 Added login functionality.
  Login_page/Capture.PNG
  Login_page/Login_background.jpg
  Login_page/login_page.html
  Login_page/login_script.js
  Login_page/login_style.css
  index.html
Labels: Hacktoberfest-accepted

#143 Authors dropdown list added with an 'Others' option
  index.html
Labels: Hacktoberfest-accepted

#148 Fixed home grid of resource.html
  resource.html
Labels: Hacktoberfest-accepted

#121 Issue no. #67
  assets/css/style.css
  index.html
  resource.css
  resource.html
Labels: Hacktoberfest-accepted

#114 Make the website responsive for mobile phone 🐱‍🏍 #35 /issue35
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: Hacktoberfest-accepted

#178 Added about page and remove loading
  about.html
  index.html
Labels: Hacktoberfest-accepted

#180 fix the alignment of navbar and made it responsive
  assets/css/style.css
  index.html
Labels: Hacktoberfest-accepted

#179 Added the header and footer in Donate book page
  assets/css/donate-book.css
  public/contact us .html
  public/donate-book.html
Labels: Hacktoberfest-accepted

#187 Fixed linting in resources HTML.
  resource.css
  resource.html
Labels: Hacktoberfest-accepted

#198 Navbar issue fixed
  assets/css/style.css
Labels: Hacktoberfest-accepted

#196 Fixed Navbar
  public/contact us .html
  public/donate-book.html
Labels: Hacktoberfest-accepted

#202 fetch upstream done and conflicts resolved
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: Hacktoberfest-accepted

#205 Shivamaddition
  resource.html
Labels: Hacktoberfest-accepted

#219 Un-necessary scroll bar is removed.
  Login_page/login_page.html
  Login_page/login_style.css
Labels: Hacktoberfest-accepted

#232 Changed the position of recommended books
  assets/css/style.css
  images/phylo1.jpg
  images/phylo2.jpg
  images/phylo3.jpg
  images/phylo4.jpg
  images/science book.jpg
  index.html
  resource.css
Labels: Hacktoberfest-accepted

#250 Changes in input field (issue no - #235)
  assets/css/style.css
Labels: Hacktoberfest-accepted

#254 Updated resources table in the home page
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: Hacktoberfest-accepted

#243 Updated logo and updated favicon image to logo
  Login_page/login_page.html
  about.html
  index.html
  public/contact us .html
  public/donate-book.html
  public/terms&conditions.html
  resource.html
Labels: Hacktoberfest-accepted

#259 About page link fixed
  resource.html
Labels: Hacktoberfest-accepted

#257 hrefBugFixed
  about.html
  public/donate-book.html
Labels: Hacktoberfest-accepted

#215 Changed home page ui as suggested in issue #195
  assets/css/.style.css.swp
  assets/css/style.css
  index.html
Labels: Hacktoberfest-accepted

#260 resolve conflict : Added missing about page link to navigation bar of donate-book.html #256
  public/donate-book.html
Labels: Hacktoberfest-accepted

#274 Fixed About page
  about.html
  assets/css/About.css
  assets/css/style.css
  public/donate-book.html
Labels: Hacktoberfest-accepted

#273 Implemented JSON fetching feature for Question Bank section!
  assets/js/BookData.js
  resource.css
  resource.html
Labels: Hacktoberfest-accepted

#279 Pointing type(Login_Page) && Minor fixes
  Login_page/login_style.css
  index.html
  public/donate-book.html
Labels: Hacktoberfest-accepted

#307 Update style.css of "Your books section"
  assets/css/style.css
  resource.css
Labels: Hacktoberfest-accepted

#296 Add ISSUE-Templates useful for maintaining
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: Hacktoberfest-accepted
