Repository SauravMukherjee44/Aec-Library-Website, pull requests merged in 2022-02, with the labels that each got.

#543 Modified FAQ section
  index.html
Labels: JWOC, Easy

#544 added more content
  images/beehive9th.jpg
  images/class9thcivics.jpg
  images/class9thgeo.jpg
  images/class9thhis.jpg
  images/first_flight10th.jpg
  images/maths10th.jpg
  images/maths9th.jpg
  images/moments9th.jpg
  resource.html
Labels: JWOC, Easy

#542 Quiz section added
  Quiz/bg.jpg
  Quiz/brain.png
  Quiz/css/game.css
  Quiz/css/style.css
  Quiz/js/game.js
  Quiz/pages/end.html
  Quiz/pages/game.html
  Quiz/quiz.svg
  index.html
Labels: JWOC, Easy

#546 Add Videos to the Resource Page and Categories the Videos using different labels #524
  resource.html
Labels: JWOC, Easy

#550 Improve the UI of the Blogs Section #523
  assets/css/style.css
  blog1.jpg
  images/blog5.jpg
  index.html
Labels: JWOC, Medium

#552 #551 remove Search Field
  about.html
  public/donate-book.html
Labels: JWOC, Easy

#553 improved the UI of the resource page
  assets/images/Navbar_background.jpg
  assets/images/Resource_Background.jpg
  resource.css
  resource.html
Labels: JWOC, Medium

#556 Design of Contact Page changed #Issue 526
  assets/css/contact us.css
  public/contact us .html
Labels: JWOC, Medium

#557 I edited resource.html file and added technical courses, as per the issue #545
  resource.css
  resource.html
Labels: JWOC, Medium

#558 Improved about page navbar
  about.html
  assets/css/About.css
Labels: JWOC, Easy

#568 Updated UI of FAQ
  assets/css/style.css
Labels: JWOC, Easy

#570 added the Title and Description to BLOGS
  index.html
Labels: JWOC, Easy

#571 Improve the UI and reduce the Loading time of Contributors Page ✨ #531
  Contributors.md
  assets/css/About.css
  assets/css/contributors.css
  contributors.html
  contributors/64.png
Labels: JWOC, Easy

#567 improving footer of about us page
  about.html
  assets/css/About.css
Labels: JWOC, Easy

#573 Sign up page UI improved
  sign up page/bg1.jpg
  sign up page/index.html
  sign up page/index.js
  sign up page/style.css
Labels: JWOC, Easy

#577 Add new features to the Library According your Ideas. #562
  resource.html
Labels: JWOC, Hard

#586 Quiz section made responsive
  Quiz/css/game.css
  Quiz/css/style.css
  Quiz/pages/game.html
Labels: JWOC, Easy

#578 issue no #559, made an audiobook section for the website.
  assets/AudioBook/Comp_Networking.mp3
  assets/AudioBook/Comp_Prog_-_the_bible.mp3
  assets/AudioBook/Comp_Prog_and_Cyber_Sec.mp3
  assets/AudioBook/Python_1.mp3
  assets/css/audiobook.css
  assets/js/audiobook.js
  index.html
Labels: JWOC, Medium

#588 Highscore feature in quiz section added
  Quiz/css/highscore.css
  Quiz/css/style.css
  Quiz/js/end.js
  Quiz/js/highscore.js
  Quiz/pages/end.html
  Quiz/pages/highscore.html
  index.html
Labels: JWOC, Easy

#589 Improved UI of Donate books page
  assets/css/donate-book.css
  public/donate-book.html
Labels: JWOC, Medium

#592 Added a volume controller in the audio book section of the resource page
  resource.css
  resource.html
Labels: JWOC, Easy

#590 Book Issue Section
  assets/css/style.css
  index.html
Labels: JWOC, Medium

#594 New pr implement the uses of search button
  index.html
Labels: JWOC, Medium

#599 Fixed speech to text icon and scroll to top btn overlap
  assets/css/style.css
Labels: JWOC, Easy

#597 Adding Login Functionality
  Login_page/login.js
  Login_page/login_page.html
  sign up page/index.html
  sign up page/index.js
  sign up page/style.css
Labels: JWOC, Hard

#612 Create a Newsletter Service for the Website #525
  index.html
Labels: JWOC, Hard

#615 Feature: Add a alert message in newsletter #614
  index.html
Labels: JWOC, Easy

#616 Improved the UI of the footer section of the contributors page and added remaining contributors
  assets/css/contributors.css
  contributors.html
Labels: JWOC, Hard

#617 Solved #610 no issue
  index.html
Labels: JWOC, Easy

#619 Reducing The Page Loading Time And Add The Modal For More Visibility Of Quiz Section
  assets/css/style.css
  index.html
Labels: JWOC, Easy

#618 Pop up msg added
  assets/css/style.css
  index.html
Labels: JWOC, Easy

#624 Create a Blogs page and Link it to the Home Page 🧑‍💻 #563
  blogs.css
  blogs.html
  index.html
Labels: JWOC, Medium
