Repository SauravMukherjee44/Aec-Library-Website, pull requests merged in 2022-03, with the labels that each got.

#644 Improved issue book section
  assets/css/style.css
  index.html
Labels: GSSoC22, Level 1

#645 docs: Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSoC22, Level 1

#660 Add questions in FAQs section
  index.html
Labels: GSSoC22, Level 1

#648 Added a scrollbar on the homepage
  Login_page/Capture.PNG
  Login_page/login_page.html
  Login_page/login_style.css
  assets/css/style.css
Labels: GSSoC22, Level 1

#664 updating newsletter form
  assets/css/style.css
  index.html
Labels: GSSoC22, Level 1

#669 Make changes to blog section of look them more elegant
  assets/css/style.css
  index.html
Labels: GSSoC22, Level 1

#672 Button Modification
  assets/css/style.css
  index.html
Labels: GSSoC22, Level 1

#683 fixed issue 626-Specify author dropdown
  index.html
Labels: GSSoC22, Level 1

#684 Fixed issue #653 : Navigate to Top Button Added : GSSoC22
  resource.css
  resource.html
Labels: GSSoC22, Level 1

#692 Issue-661 resolved
  about.html
  assets/css/About.css
Labels: GSSoC22, Level 1

#697 Modified the UI (Basically focused on font) of Resources Page.
  resource.css
Labels: GSSoC22, Level 1

#701 Fixed the bug
  index.html
Labels: GSSoC22, Level 1

#709 worked on volume button and social media icon which is in footer
  resource.css
  resource.html
Labels: GSSoC22, Level 1

#714 Fixed issue #710 : Bug Report: Transition in Go to Top button of Home Page. Also hover feature introduced: GSSoC22
  assets/css/style.css
  index.html
Labels: GSSoC22, Level 1

#717 UI Improvement Donate Book Page
  .vscode/settings.json
  assets/css/donate-book.css
  public/donate-book.html
Labels: GSSoC22, level 2

#705 Resolve the bug in donate-books section
  assets/css/donate-book.css
  public/donate-book.html
Labels: GSSoC22, Level 1

#728 Fixing all logo links to the main page of the website
  Contributors.md
  Forgot_Password/index.html
  Forgot_Password/recovery.html
  Login_page/login_page.html
  index.html
  resource.html
Labels: GSSoC22, Level 1

#730 Fixes broken images and shields in documentation on GitHub Mobile App
  CodeIN_Logo.png
  README.md
Labels: GSSoC22, Level 1

#731 #719 fixed footer section in contributors page
  contributors.html
Labels: GSSoC22, Level 1

#746 Modified Sign In Button
  Login_page/login_style.css
  sign up page/index.html
  sign up page/style.css
Labels: GSSoC22, Level 1

#766 Hover effect NCERT Books
  resource.css
Labels: GSSoC22, Level 1

#765 AddedThumbnail
  resource.html
Labels: GSSoC22, Level 1

#750 quiz section fixed
  Quiz/js/game.js
Labels: GSSoC22, Level1

#787 added missing Opening h1 and div tag
  assets/css/contributors.css
  contributors.html
  index.html
Labels: GSSoC22, Level1

#779 #773 fixed FAQ in Homepage
  index.html
Labels: GSSoC22, Level1

#768 Customized General message section of resource page(issue #682)
  resource.html
Labels: GSSoC22, Level1

#814 Added missing navigation links in resources page.
  resource.css
  resource.html
Labels: GSSoC22, Level1
