Repository SauravMukherjee44/Aec-Library-Website, pull requests merged in 2022-10, with the labels that each got.

#875 Linked images of Web development Course properly
  resource.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#881 Made minor changes to the Book Donation Form as mentioned
  public/donate-book.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#882 Read More Button (blog page) Placement in Card fixed.
  blogs.css
  blogs.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#866 The width of the main website was changed
  assets/css/style.css
  index.html
  style.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#893 Made changes to navbar, issue and choose and read books
  Contributors.md
  assets/css/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#907 Add this New YouTube Link: https://bit.ly/CodeINYouTube and remove th…
  about.html
  blogs.html
  contributors.html
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#916 Update ncert.css
  ncert.css
Labels: good first issue, Hacktoberfest

#914 change sign-up.html page add some CSS and made the buttons much better
  sign-up-page/index.html
  sign-up-page/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#904 some more technical blogs added
  blogs.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#944 Changes about page footer: enhanced visibility & donate book page nav color
  about.html
  assets/css/About.css
  assets/css/donate-book.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#938 Added Indian Cities and added states & cities of Australia & Canada
  assets/js/Donate_Book.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#933 Bug: Wrong Journals, Referrals and E-books count on home page
  assets/js/script.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#942 Bug Report: Fix Browser Console Errors
  Login_page/login.js
  Quiz/js/game.js
  assets/css/audiobook.css
  assets/css/style.css
  assets/js/audiobook.js
  assets/js/script.js
  index.html
  recommended_books.js
  sign-up-page/index.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#952 Hover feature to Subscribe button
  assets/css/style.css
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#919 The GitHub Icon is now added in place of text
  resource.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#967 Modified links properly
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#960 Fixed Navbar links and Read books section.
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#959 Resource.html updated with cbse notes and more #903
  cbse_notes/images/ACC12.jpg
  cbse_notes/images/CH11.jpg
  cbse_notes/images/CS11.jpg
  cbse_notes/images/GEO11.heic
  cbse_notes/images/M11.jpg
  cbse_notes/images/PHY11.png
  resource.css
  resource.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#949 Added Textarea in Address
  public/donate-book.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#948 Navbar toggle bug in blogs.html
  blogs.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#926 I have added all Cities under Madhya Pradesh State
  assets/js/Donate_Book.js
Labels: Hacktoberfest-accepted, Hacktoberfest

#922 Update donate-book.html
  public/donate-book.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#918 Update style.css
  assets/css/style.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#1011 Update blogs.html
  blogs.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1021 grammatical error fixed
  index.html
Labels: good first issue, Hacktoberfest, ☑ status : Approved by 1 maintainer

#1019 Updated High-score Section.
  Quiz/css/highscore.css
  Quiz/css/style.css
  index.html
Labels: enhancement, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1018 Added programming lang. courses and resolved broken images
  resource.html
Labels: good first issue, Hacktoberfest, ☑ status : Approved by 1 maintainer

#1007 added footer year using javascript
  about.html
  blogs.html
  cbse_notes.html
  contributors.html
  index.html
  ncert.html
  resource.html
Labels: bug, good first issue, ☑ status : Approved by 1 maintainer

#997 Added Icons Instead Of Play button In Listen To Audio Books Section
  Samplepapers/play.png
  assets/css/audiobook.css
  assets/css/style.css
  assets/js/audiobook.js
  index.html
  media/pause.png
  media/play.png
Labels: enhancement, good first issue, Hacktoberfest, ☑ status : Approved by 1 maintainer

#986 Modified 'Yours Books' Section correctly.
  assets/css/style.css
Labels: bug, good first issue, Hacktoberfest, ☑ status : Approved by 1 maintainer

#968 Resource page Header UI change and Minor bug fix in Home page
  index.html
  resource.css
  resource.html
Labels: bug, Hacktoberfest, ☑ status : Approved by 1 maintainer

#1027 Changes made
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1042 Update blogs.html
  blogs.html
Labels: Hacktoberfest-accepted, Hacktoberfest, 🚦 status : Requested changes

#1041 changed login_style.css container image
  Login_page/Untitled design (3).png
  Login_page/images.jfif
  Login_page/login_img.jpg
  Login_page/login_style.css
  images/loginpage_img.jpg
  images/sign_loginpg.png
Labels: duplicate, Hacktoberfest-accepted, Hacktoberfest, 🚦 status : Requested changes

#1030 Adding curve to borders, enhancing UI
  assets/css/style.css
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1040 [Solved] - All Buttons Routing Problems are solved.
  about.html
  blogs.css
  resource.css
  resource.html
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1032 [Bug-in code-fixed]closing unclosed bracket in css file #1031
  assets/css/style.css
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1029 Updated the instagram link in the resources page
  resource.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1044 Enhanced the UI of the Resources Page
  resource.css
  resource.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1052 Fixed future date's shown in issuebook section and some navigation bugs in home page
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1068 Blogs added
  blogs.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1054 Fixed #1053
  recommended_books.js
Labels: enhancement, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1045 Updated login page to remove log out button
  Login_page/login_page.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#1037 updating books of class 8th in NCERT section
  ncert.html
Labels: good first issue, Hacktoberfest

#1077 Fix Responsiveness
  Quiz/css/style.css
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1065 Fixed Typo
  index.html
Labels: Hacktoberfest-accepted, Hacktoberfest

#1047 updated the css code for contact us footer was not aligned at bottom it was floating
  assets/css/contact us.css
Labels: Hacktoberfest-accepted, Hacktoberfest

#1039 Fixed footer section of index.html
  index.html
Labels: bug, good first issue, 🚦 status : Requested changes

#1072 Home page is now Responsive
  assets/css/style.css
  blogs.css
  index.html
Labels: enhancement, Hacktoberfest-accepted, Hacktoberfest

#1091 Fixed footer and navbar of the contact us page
  assets/css/contact us.css
Labels: Hacktoberfest-accepted, Hacktoberfest
