Repository SauravMukherjee44/Aec-Library-Website, pull requests merged in 2023-06, with the labels that each got.

#1291 hover effect added
  resource.css
  resource.html
Labels: Level1, gssoc23

#1314 Added more books
  images/bookimage19.jpg
  images/bookimage20.png
  images/bookimage21.jpg
  images/bookimage22.png
  images/bookimage23.png
  images/bookimage24.png
  recommended_books.json
Labels: Level1, gssoc23

#1298 Blog card Enhancement #1294 Fixed
  blogs.css
Labels: Level1, gssoc23

#1327 Made resources page responsive
  resource.css
  resource.html
Labels: level2, gssoc23

#1261 Read Book button issue #1260 Fixed
  assets/css/style.css
Labels: level1, gssoc23

#1268 Made 'Blogs' page responsive
  blogs.css
Labels: level1, gssoc23

#1273 FAQ added to Navbar
  assets/css/style.css
  index.html
Labels: level1, gssoc23

#1278 Add DSA Revision Guide
  Notes/DSA Revision Guide.pdf
Labels: level1, gssoc23

#1244 Faq section updated
  assets/css/style.css
  resource.css
  resource.html
Labels: level2, gssoc23

#1391 #issue 1239 Faq section added
  about.html
  assets/css/faq.css
  public/faq.html
Labels: level2, gssoc23
