Repository SauravMukherjee44/Aec-Library-Website, pull requests merged in 2023-05, with the labels that each got.

#1122 Some Images are not visible #1118 Bug Resolved
  resource.html
Labels: gssoc23

#1129 improved ui of blog page
  blogs.css
  blogs.html
  recommended_books.js
Labels: gssoc23

#1131 Improve footer responsiveness
  assets/css/contributors.css
  contributors.html
Labels: Level1, gssoc23

#1137 Footer Positioning #1136 Issue Fixed
  assets/css/style.css
Labels: Level1, gssoc23

#1148 Blog Section Footer Element behaviour #1146 Fixed
  assets/css/About.css
Labels: Level1, gssoc23

#1158 The Nav-Items open on a new tab hence Reducing the Loading Time of Website
  index.html
Labels: Level1, gssoc23

#1166 Improve UI of Search bar section of Contributors page issue#1144 reso…
  assets/css/contributors.css
  contributors.html
Labels: Level2, gssoc23

#1165 added back-to-top button
  assets/css/contributors.css
  assets/css/donate-book.css
  blogs.css
  blogs.html
  contributors.html
  public/donate-book.html
Labels: Level1, gssoc23

#1164 Bug Fixed
  assets/css/contact us.css
Labels: Level1, gssoc23

#1153 Added book of JavaScript
  images/bookimage11.png
  images/bookimage12.png
  images/bookimage13.png
  images/bookimage14.png
  images/bookimage15.png
  recommended_books.json
Labels: Level2, gssoc23

#1192 Improved issue form by added JS validation issue#1143 resolved
  assets/css/style.css
  index.html
Labels: Level2, gssoc23

#1205 added the get a book page
  about.html
  public/getabook.html
Labels: Level1, gssoc23

#1204 Added a table of content to README.md
  README.md
Labels: Level1, gssoc23

#1193 Quiz background changes
  .vscode/settings.json
  Quiz/css/style.css
  Quiz/js/game.js
  Quiz/pages/end.html
  Quiz/pages/game.html
  Quiz/pages/highscore.html
  index.html
Labels: Level1, gssoc23

#1183 Footer of resource page need some improvement #1182 Fixed
  resource.css
  resource.html
Labels: Level1, gssoc23

#1177 Corrected typos and grammatical errors #1150
  CODE_OF_CONDUCT.md
  README.md
  about.html
  blogs.html
  index.html
  public/contact us .html
  public/privacy-policy.html
  public/terms&conditions.html
Labels: Level1, gssoc23

#1215 Fix Text in README
  README.md
Labels: Level1, gssoc23

#1216 loginpage_fucntionality
  Login_page/login.js
  Login_page/login_page.html
  Login_page/login_style.css
Labels: Level1, gssoc23

#1222 RECOMMEDED SECTION UPDATED
  assets/css/style.css
  index.html
  recommended_books.js
Labels: Level1, gssoc23

#1226 Modified scrollbar (Issue -1179)
  assets/css/style.css
Labels: Level1, gssoc23

#1217 Changes made on quick quiz made as mentioned
  Quiz/css/game.css
  Quiz/css/style.css
  Quiz/pages/end.html
  Quiz/pages/game.html
Labels: Level1, gssoc23

#1234 Nav Link Hover Effect, Borders, Font, Alignment, and Scrollbar Styling
  assets/css/style.css
  index.html
Labels: Level3, gssoc23

#1259 Solved: #1219 - Updated navigation icon and added responsiveness to the login and signup pages for all devices.
  Contributors.md
  Login_page/style.css
  sign-up-page/index.html
  sign-up-page/style.css
Labels: Level1, gssoc23

#1254 Addition of section links to Faq section
  assets/css/style.css
  index.html
Labels: Level1, gssoc23

#1209 Add Interview Preparation Books in Website
  images/bookimage16.png
  images/bookimage17.png
  images/bookimage18.jpg
  recommended_books.js
  recommended_books.json
Labels: Level1, gssoc23

#1186 Formatting the datatable in home page and enhancing the readability by changing the css
  about.html
  assets/css/About.css
  assets/css/donate-book.css
  assets/css/style.css
  index.html
  public/donate-book.html
  recommended_books.js
Labels: Level1, gssoc23

#1236 AEC-Library Tag in Resource Page #1220 fixed
  resource.css
Labels: Level1, gssoc23
